name: Flutter iOS Simulator Build

on:
  push:
    branches:
      - main # sesuaikan dengan branch yang ingin digunakan
  pull_request:

jobs:
  build-ios-simulator:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.5.0' # sesuaikan dengan versi Flutter kamu

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyzer
      run: flutter analyze

    - name: Build iOS for Simulator
      run: flutter build ios --debug --simulator
